version: "3.9"

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - "./db.env"

# docker-compose exec db mysql -u test_user -D test_database -p
# rogin pass
